image: ruby:3.2.0

stages:
  - test

test:
  stage: test
- name: Install Bundler 2.3.27
  run: gem install bundler:2.3.27

- name: Use required Bundler version
  run: bundle _2.3.27_ install

  script:
    - gem install bundler
    - bundle
    - pwd
    - rspec
